spring:
  datasource:
    url: jdbc:postgresql://donations-db.cxoaaw8g4mh7.us-east-2.rds.amazonaws.com:5432/postgres
    username: dbamin
    password: "donationsdb1$"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ðŸ‘ˆ THIS creates/updates tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true