spring:
  application:
    name: mc-donation
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: email-smtp.us-east-2.amazonaws.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: email-smtp.us-east-2.amazonaws.com


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  servlet:
    context-path: '/donation/v1'

jwt:
  secret: ${JWT_SECRET:myDefaultLocalSecretKey12345678901234567890}
  expiration: ${JWT_EXPIRATION:900000}

messaging:
  verification-url: ${MESSAGING_VERIFICATION_URL:http://localhost/test}